### ISSUE TITLE
Support filters on all types

### ISSUE THREAD

**Issue by alex0ptr** [qaware/qaway-linter#4]
I would like to support filters e.g. on structs and interfaces and potentially any other type definition:

```
            interfaces:
              filters:
                minLinesOfCode: 10
              params:
                requireHeadlineComment: true
                requireMethodComment: true
            structs:
              filters:
                minLinesOfCode: 10
              params:
                requireHeadlineComment: true
                requireFieldComment: false
```
